/*
 * Copyright (c) 2018, Alliance for Open Media. All rights reserved
 *
 * This source code is subject to the terms of the BSD 2 Clause License and
 * the Alliance for Open Media Patent License 1.0. If the BSD 2 Clause License
 * was not distributed with this source code in the LICENSE file, you can
 * obtain it at www.aomedia.org/license/software. If the Alliance for Open
 * Media Patent License 1.0 was not distributed with this source code in the
 * PATENTS file, you can obtain it at www.aomedia.org/license/patent.
 */
#ifndef AOM_CONFIG_H_
#define AOM_CONFIG_H_
#define ARCH_ARM 0
#define ARCH_MIPS 0
#define ARCH_X86 0
#define ARCH_X86_64 0
#define CONFIG_ACCOUNTING 0
#define CONFIG_AMVR 0
#define CONFIG_ANALYZER 0
#define CONFIG_AOM_QM 1
#define CONFIG_AOM_QM_EXT 0
#define CONFIG_AV1 1
#define CONFIG_AV1_DECODER 1
#define CONFIG_AV1_ENCODER 0
#define CONFIG_BGSPRITE 0
#define CONFIG_BIG_ENDIAN 0
#define CONFIG_BITSTREAM_DEBUG 0
#define CONFIG_CDF_STORAGE_REDUCTION 0
#define CONFIG_CFL 1
#define CONFIG_CICP 0
#define CONFIG_COEFFICIENT_RANGE_CHECKING 0
#define CONFIG_COLORSPACE_HEADERS 0
#define CONFIG_DEBUG 0
#define CONFIG_DECODE_PERF_TESTS 0
#define CONFIG_DEPENDENT_HORZTILEGROUPS 0
#define CONFIG_DEPENDENT_HORZTILES 0
#define CONFIG_DIST_8X8 1
#define CONFIG_DUAL_FILTER 1
#define CONFIG_EIGHTH_PEL_MV_ONLY 0
#define CONFIG_ENCODE_PERF_TESTS 0
#define CONFIG_ENTROPY_STATS 0
#define CONFIG_EOB_FIRST 0
#define CONFIG_EXT_COMP_REFS 1
#define CONFIG_EXT_DELTA_Q 1
#define CONFIG_EXT_INTRA_MOD 1
#define CONFIG_EXT_INTRA_MOD2 1
#define CONFIG_EXT_PARTITION 0
#define CONFIG_EXT_PARTITION_TYPES 0
#define CONFIG_EXT_QM 0
#define CONFIG_EXT_SKIP 0
#define CONFIG_EXT_TILE 0
#define CONFIG_EXT_WARPED_MOTION 1
#define CONFIG_FAST_SGR 1
#define CONFIG_FILEOPTIONS 1
#define CONFIG_FILM_GRAIN 0
#define CONFIG_FILTER_INTRA 0
#define CONFIG_FP_MB_STATS 0
#define CONFIG_FRAME_SIZE 1
#define CONFIG_FWD_KF 0
#define CONFIG_GCC 1
#define CONFIG_GCOV 0
#define CONFIG_GPROF 0
#define CONFIG_HASH_ME 0
#define CONFIG_HIGHPRECISION_INTBUF 0
#define CONFIG_HORZONLY_FRAME_SUPERRES 1
#define CONFIG_INSPECTION 0
#define CONFIG_INTERNAL_STATS 0
#define CONFIG_INTER_STATS_ONLY 0
#define CONFIG_INTRABC 0
#define CONFIG_INTRA_EDGE 1
#define CONFIG_JNT_COMP 0
#define CONFIG_LIBYUV 1
#define CONFIG_LOOPFILTERING_ACROSS_TILES 1
#define CONFIG_LOOPFILTERING_ACROSS_TILES_EXT 1
#define CONFIG_LOOPFILTER_LEVEL 1
#define CONFIG_LOOP_RESTORATION 1
#define CONFIG_LOWBITDEPTH 1
#define CONFIG_LOWPRECISION_BLEND 0
#define CONFIG_LV_MAP 0
#define CONFIG_MAX_TILE 1
#define CONFIG_MFMV 1
#define CONFIG_MISMATCH_DEBUG 0
#define CONFIG_MONO_VIDEO 0
#define CONFIG_MSVS 0
#define CONFIG_MULTITHREAD 1
#define CONFIG_NEW_QUANT 0
#define CONFIG_NO_FRAME_CONTEXT_SIGNALING 0
#define CONFIG_OBU 0
#define CONFIG_OBU_NO_IVF 0
#define CONFIG_OBU_SIZING 0
#define CONFIG_OPT_REF_MV 0
#define CONFIG_OS_SUPPORT 1
#define CONFIG_PALETTE_THROUGHPUT 1
#define CONFIG_PIC 0
#define CONFIG_Q_ADAPT_PROBS 0
#define CONFIG_RD_DEBUG 0
#define CONFIG_REALTIME_ONLY 0
#define CONFIG_RECT_TX_EXT 1
#define CONFIG_RECT_TX_EXT_INTRA 1
#define CONFIG_REFERENCE_BUFFER 1
#define CONFIG_RUNTIME_CPU_DETECT 1
#define CONFIG_SCALABILITY 0
#define CONFIG_SEGMENT_GLOBALMV 1
#define CONFIG_SEGMENT_PRED_LAST 1
#define CONFIG_SHARED 0
#define CONFIG_SHORT_FILTER 1
#define CONFIG_SIZE_LIMIT 0
#define CONFIG_SPATIAL_RESAMPLING 1
#define CONFIG_SPATIAL_SEGMENTATION 1
#define CONFIG_STATIC 1
#define CONFIG_TILE_INFO_FIRST 0
#define CONFIG_TIMING_INFO_IN_SEQ_HEADERS 0
#define CONFIG_TMV 1
#define CONFIG_TX64X64 1
#define CONFIG_UNIT_TESTS 0
#define CONFIG_WEBM_IO 1
#define HAVE_AVX 0
#define HAVE_AVX2 0
#define HAVE_DSPR2 0
#define HAVE_FEXCEPT 1
#define HAVE_MIPS32 0
#define HAVE_MIPS64 0
#define HAVE_MMX 0
#define HAVE_MSA 0
#define HAVE_NEON 0
#define HAVE_NEON_ASM 0
#define HAVE_PTHREAD_H 1
#define HAVE_SSE 0
#define HAVE_SSE2 0
#define HAVE_SSE3 0
#define HAVE_SSE4_1 0
#define HAVE_SSSE3 0
#define HAVE_UNISTD_H 1
#define HAVE_WXWIDGETS 0
#define INLINE inline
#define RESTRICT 
#endif  /* AOM_CONFIG_H_ */
